### ISSUE TITLE
Setup Environment

### ISSUE THREAD

**Issue by jonatas-freire** [Modal-GR/react-ui-componentes#1]
## Tasks
- [x] Configure package.json and .gitignore
- [x] Configure React and Typescript
- [x] Configure storybook
- [x] Configure tests with jest
- [x] Create example component
- [x] Configure build lib
- [x] Create github actions to publish in npm and yarn
